image: Visual Studio 2019 Preview

install:
  - cinst fake
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: fake.exe run build.fsx --parallel 3

artifacts:
- path: \artifacts\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: brtaeZJpx3iIaGtMCfjaYJqtOnLStmEr9HzeHveiy4psMBxH0PZ/kY2Lq9/EiME9