image: Visual Studio 2019 Preview

install:
  - cinst fake
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: fake.exe run build.fsx --parallel 3

artifacts:
- path: \artifacts\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: DZwv3NyRhJ2sshB2omaSvyte+34C4m/AWp3eUjeCOr6aWdzACpziqXtsL9i8/jKz